name: "ZAP Baseline Scan"

on:
  # Runs every day At 01:00.
  schedule:
    - cron:  '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-baseline@66042c8e7e24680119199a017e5b0e8603bf4dae # v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://app.dev.rewind.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'
