name: "ZAP Baseline Scan"

on:
  # Runs every day At 01:00.
  # schedule:
  #   - cron:  '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      discussions: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set scan issue title
        uses: actions/github-script@v7
        id: issue-title
        with:
          script: return `ZAP Scan Baseline Report - Dev`
          result-encoding: string
      
      - name: Scan execution Issue Title
        run: echo "${{steps.issue-title.outputs.result}}"

      - name: ZAP Scan
        uses: zaproxy/action-baseline@66042c8e7e24680119199a017e5b0e8603bf4dae # v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://app.dev.rewind.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'
          issue_title: '${{steps.issue-title.outputs.result}}'
